// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4MawwSm39R2uSnnzwAueqp-8sBQWL2xI',
    appId: '1:393854054518:web:f0b7985a4538a673beaf57',
    messagingSenderId: '393854054518',
    projectId: 'fir-sample-c629f',
    authDomain: 'fir-sample-c629f.firebaseapp.com',
    storageBucket: 'fir-sample-c629f.appspot.com',
    measurementId: 'G-3H7TWQKJ9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ueatYKV_7IqlegIUHDgU6U9jPveEXuM',
    appId: '1:393854054518:android:4b495049c1bc84c1beaf57',
    messagingSenderId: '393854054518',
    projectId: 'fir-sample-c629f',
    storageBucket: 'fir-sample-c629f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw0VISJ_IbYjoh5zq2gHEjvBa7_IilB30',
    appId: '1:393854054518:ios:c3fecadda3e9f011beaf57',
    messagingSenderId: '393854054518',
    projectId: 'fir-sample-c629f',
    storageBucket: 'fir-sample-c629f.appspot.com',
    iosBundleId: 'com.example.firebaseSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw0VISJ_IbYjoh5zq2gHEjvBa7_IilB30',
    appId: '1:393854054518:ios:c3fecadda3e9f011beaf57',
    messagingSenderId: '393854054518',
    projectId: 'fir-sample-c629f',
    storageBucket: 'fir-sample-c629f.appspot.com',
    iosBundleId: 'com.example.firebaseSample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4MawwSm39R2uSnnzwAueqp-8sBQWL2xI',
    appId: '1:393854054518:web:1c8ed0493ba63098beaf57',
    messagingSenderId: '393854054518',
    projectId: 'fir-sample-c629f',
    authDomain: 'fir-sample-c629f.firebaseapp.com',
    storageBucket: 'fir-sample-c629f.appspot.com',
    measurementId: 'G-0H27P4S73N',
  );

}